# Generated by Django 5.0.1 on 2024-01-19 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        models.DateField(auto_now_add=True)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        models.DateField(auto_now_add=True)
                    )
                ]
            ),
        ),
    ]
